### ISSUE TITLE
Move into Monorepo

### ISSUE THREAD

**Issue by Golodhros** [britecharts/britecharts#951]
Move Britecharts into a monorepo setup.

- [x] Renovate
- [x] yarn 3 
- [x] Separate packages in a mono repo style 
- [x] Babel setup
- [x] Storybook per library (stand-alone, react, vue, etc) or one for all. #996
- [x] eslint for mono repo configuration
- [x] stylelint
- [x] Prettier
- [x] Remove karma in favor of Jest #952 
- [x] Documentation to [docusourious](https://docusaurus.io/) #395 
- [x] Push changes to Main (not Master)
- [ ] Release per package?

**Comment by gagoar** [comment]
proposal for the monorepo:
The packages could be:
Monorepo Plan
- @britecharts/core
	- Current Britecharts
	- Types
	- TestDataBuilders
	- Storybook/core
- @britecharts/docs
	- Tutorials
	- HowTo Guides
	- API Docs
	- Storybook/common
- @britecharts/wrappers
	- Wrappers from BCR
- @britecharts/react
	- BCR components
	- Storybook/react
- @britecharts/angular
	- Angular components
	- Storybook/angular
- @britecharts/vue
	- Vue components
	- Storybook/vue
- @britechrarts/svelte
	- Svelte components
	- Storybook/svelte
